#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

packages=(
        fd
        ripgrep
        stow
)

for package in "${packages[@]}"; do
    echo "Installing ${package}"
    /home/linuxbrew/.linuxbrew/bin/brew install "$package"
done

for dir in "$(ls -d */)"; do
    stow "$dir" --dotfiles
done

echo "done"

